version: "3.9"

services:

  bomi_server:
    build:
      context: ./bomi_fama_nodejs
      dockerfile: Dockerfile.dockerfile
    #image: hypothe/node_bomi_fama:test
    networks:
      - bomi-fama
    ports:
      - "8080:4242"
    entrypoint: ["npm", "start"]
    

  bomi_pyclient:
    build:
      context: ./markerlessBoMI_FaMa
      dockerfile: Dockerfile.dockerfile
    #image: hypothe/bomi_fama:test-server
    environment:
      - BOMI_SERVER_NAME=bomi_server # used by the test_socket script
      - DISPLAY
      - XDG_RUNTIME_DIR
      - QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/video0:/dev/video0
    privileged: true
    networks:
      - bomi-fama
    ports:
      - "8081:4242"
    entrypoint: ["python", "main_mechanism.py"]
    depends_on:
      - bomi_server
    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  bomi-fama: {}