version: "3.9"

services:

  bomi_server:
    container_name: bomi_server
    build:
      context: ./bomi_fama_nodejs
      dockerfile: Dockerfile.dockerfile
    networks:
      - bomi-fama
    ports:
      - "8042:4242"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    entrypoint: ["npm", "start"]
    

  bomi_pyclient:
    build:
      context: ./markerlessBoMI_FaMa
      dockerfile: Dockerfile.dockerfile
    environment:
      - BOMI_SERVER_NAME=bomi_server # used by the test_socket script
      - DISPLAY
      - XDG_RUNTIME_DIR
      - QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/video0:/dev/video0
    privileged: true

    networks:
     - bomi-fama
    entrypoint: ["python", "main_mechanism.py"]
    depends_on:
      - bomi_server
    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  bomi-fama: {}