version: "3.9"

services:

  bomi_server:
    build:
      context: ./bomi_fama_nodejs
      dockerfile: Dockerfile.dockerfile
    network_mode: "host"
    #networks:
    #  - bomi-fama
    #ports:
    #  - "8042:4242"
    #  - "8043:4243"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

    entrypoint: ["npm", "start"]
    

  bomi_pyclient:
    build:
      context: ./markerlessBoMI_FaMa
      dockerfile: Dockerfile.dockerfile
    environment:
      #- BOMI_SERVER_NAME=bomi_server # used by the test_socket script
      - DISPLAY
      - XDG_RUNTIME_DIR
      - QT_X11_NO_MITSHM=1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /dev/video0:/dev/video0
    privileged: true
    network_mode: "host"

    #networks:
    # - bomi-fama
    #ports:
    #  - "8142:4242"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["python", "main_mechanism.py"]
    depends_on:
      - bomi_server
    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              capabilities: [gpu]

  bomi_webgl:
    container_name: unity-webgl
    image: unity-webgl
    build: 
      context: ./unity-docker-example
      #args:
      #  - BOMI_SERVER_NAME=bomi_server
    #ports:
    #  - "8080:80"
    depends_on:
      - bomi_server
    #  - "8243:4243"
    network_mode: "host"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #networks:
    # - bomi-fama

#networks:
#  bomi-fama: {}